{{- $postgresPassword := required "secrets.postgresPassword must be provided" .Values.secrets.postgresPassword }}
{{- $scrobSecretKey := required "secrets.scrobSecretKey must be provided" .Values.secrets.scrobSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ $postgresPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-scrob-secret
  labels:
    app.kubernetes.io/name: scrob
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  SECRET_KEY: {{ $scrobSecretKey | quote }}
  DATABASE_URL: {{ printf "postgresql+asyncpg://%s:%s@%s-postgres:5432/%s" .Values.postgres.username $postgresPassword .Release.Name .Values.postgres.database | quote }}
