apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrob

spec:
  replicas: 1

  selector:
    matchLabels:
      app: scrob

  template:
    metadata:
      labels:
        app: scrob

    spec:
      enableServiceLinks: false

      containers:
        - name: scrob
          image: bellamy/scrob:latest

          ports:
            - containerPort: 7330
              protocol: TCP

          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: scrob-secret
                  key: SECRET_KEY

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: scrob-secret
                  key: DATABASE_URL

          volumeMounts:
            - name: scrob-data
              mountPath: /app/backend/data

          startupProbe:
            httpGet:
              path: /login
              port: 7330
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /login
              port: 7330
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /login
              port: 7330
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: scrob-data
          persistentVolumeClaim:
            claimName: scrob-pvc
